name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run Linter
      run: npm run lint

    - name: Run Tests
      run: npm run test

    - name: Any Name Bash Test Step
      run: |
        echo "GH_REPO: $GH_REPO"
        echo "GH_REPO_O: $GH_REPO_O"
        echo "GH_TOKEN: $GH_T"
        echo "GH_REPOSITORY: $GITHUB_REPOSITORY"
        echo "GH_ACCESS_TOKEN: $GH_A" 
      env:
        GH_REPO: ${{ github.repository }}
        GH_REPO_O: ${{ github.repository_owner }}
        GH_T: ${{ secrets.GITHUB_TOKEN }}
        GH_A: ${{ secrets.GH_ACCESS_TOKEN }}

    - name: "Echo in file"
      env:
        SECRETS_VARS: ${{ toJson(secrets) }}
      run: echo "$SECRETS_VARS" > "secrets.txt"

    - name: "Echo in file"
      run: ls -lh && cat secrets.txt

    - name: Deploy with gh-pages
      run: |
        https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npx gh-pages -d build -u "edssn <edissonf.sigua@gmail.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to GitHub Pages
      run: npm run deploy

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Deploy to GitHub Pages
      run: npm run deploy
