name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run Linter
      run: npm run lint

    - name: Run Tests
      run: npm run test

    - name: Set username
      run: |
        cd ci-cd-software-developers-course
        git config --local user.email "edissonf.sigua@gmail.com"
        git config --local user.name "edssn"

    - name: Deploy to GitHub Pages
      run: npm run deploy

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Deploy to GitHub Pages
      run: npm run deploy
